#!/bin/bash

##
##                  Y.                      _
##                  YiL                   .```.
##                  Yii;                .; .;;`.
##                  YY;ii._           .;`.;;;; :
##                  iiYYYYYYiiiii;;;;i` ;;::;;;;
##              _.;YYYYYYiiiiiiYYYii  .;;.   ;;;
##           .YYYYYYYYYYiiYYYYYYYYYYYYii;`  ;;;;
##         .YYYYYYY$$YYiiYY$$$$iiiYYYYYY;.ii;`..
##        :YYY$!.  TYiiYY$$$$$YYYYYYYiiYYYYiYYii.
##        Y$MM$:   :YYYYYY$!"``"4YYYYYiiiYYYYiiYY.
##     `. :MM$$b.,dYY$$Yii" :'   :YYYYllYiiYYYiYY
##  _.._ :`4MM$!YYYYYYYYYii,.__.diii$$YYYYYYYYYYY
##  .,._ $b`P`     "4$$$$$iiiiiiii$$$$YY$$$$$$YiY;
##     `,.`$:       :$$$$$$$$$YYYYY$$$$$$$$$YYiiYYL
##      "`;$$.    .;PPb$`.,.``T$$YY$$$$YYYYYYiiiYYU:
##      ;$P$;;: ;;;;i$y$"!Y$$$b;$$$Y$YY$$YYYiiiYYiYY
##      $Fi$$ .. ``:iii.`-":YYYYY$$YY$$$$$YYYiiYiYYY
##      :Y$$rb ````  `_..;;i;YYY$YY$$$$$$$YYYYYYYiYY:
##       :$$$$$i;;iiiiidYYYYYYYYYY$$$$$$YYYYYYYiiYYYY.
##        `$$$$$$$YYYYYYYYYYYYY$$$$$$YYYYYYYYiiiYYYYYY
##        .i!$$$$$$YYYYYYYYY$$$$$$YYY$$YYiiiiiiYYYYYYY
##       :YYiii$$$$$$$YYYYYYY$$$$YY$$$$YYiiiiiYYYYYYi'
##
##          XOXO
##  		Jesse B.
##

# Source function library
. /etc/init.d/functions

#startup values
dir=/usr/local/etc/7daysManager/
log=/usr/local/etc/7daysManager/var/log/7daysManager.log

#verify that the executable exists
test -x 7daysManager.php || exit 0RETVAL=0

#
#	Set daemon variables
#
prog="7daysManager"
proc=7daysManager.lock
bin=$dir/7daysManager.php

start() {
# Check if 7daysManager is already running
  if [ ! -f $proc ]; then
    echo -n $"Starting $prog: "
    daemon $bin --log=$log
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch $proc
    echo
  fi

  return $RETVAL
}

stop() {
  echo -n $"Stopping $prog: "
  ps -ef | grep $prog | grep [p]hp | awk '{print $2}' | xargs kill -9
  RETVAL=$?
  [ $RETVAL -eq 0 ] && rm -f $proc
  echo

  return $RETVAL
}

restart() {
  stop
  start
}

reload() {
  restart
}

status_at() {
  status $bin
}

case "$1" in
start)
  start
  ;;
stop)
  stop
  ;;
reload|restart)
  restart
  ;;
condrestart)
  if [ -f $proc ]; then
    restart
  fi
  ;;
status)
  status_at
  ;;
*)

echo $"Usage: $0 {start|stop|restart|condrestart|status}"

exit 1
esac

exit $?
exit $RETVAL
